name: Sync Jira with GitHub Issue
on:
  issues:
    types:
      - opened
      - edited
      - closed

jobs:
  sync-jira-issue:
    uses: kakaotech-19/.github/.github/workflows/create-jira-issue.yml@main
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
